import { axiosForBackend } from '@client/src/api';
import type { NoticeItemFull, BannerFull, SiteSettings, PaginatedResponse } from '@shared/api.interface';
export const listNotices = async (params: { page?: number; pageSize?: number }): Promise<PaginatedResponse<NoticeItemFull>> => (await axiosForBackend.get('/api/admin/notices', { params })).data;
export const createNotice = async (data: { title: string; content: string; status: 'published' | 'draft' }): Promise<{ id: string }> => (await axiosForBackend.post('/api/admin/notices', data)).data;
export const updateNotice = async (id: string, data: { title: string; content: string; status: 'published' | 'draft' }): Promise<{ success: true }> => (await axiosForBackend.put(`/api/admin/notices/${id}`, data)).data;
export const deleteNotice = async (id: string): Promise<{ success: true }> => (await axiosForBackend.delete(`/api/admin/notices/${id}`)).data;
export const getNoticeDetail = async (id: string): Promise<NoticeItemFull & { content: string }> => (await axiosForBackend.get(`/api/admin/notices/${id}`)).data;
export const getSiteSettings = async (): Promise<SiteSettings> => (await axiosForBackend.get('/api/admin/site-settings')).data;
export const saveSiteSettings = async (data: SiteSettings): Promise<{ success: true }> => (await axiosForBackend.put('/api/admin/site-settings', data)).data;
export const listBanners = async (): Promise<{ items: BannerFull[] }> => (await axiosForBackend.get('/api/admin/banners')).data;
export const createBanner = async (data: { title: string; imageUrl: string; linkUrl: string; sortOrder: number }): Promise<{ id: string }> => (await axiosForBackend.post('/api/admin/banners', data)).data;
export const updateBanner = async (id: string, data: { title: string; imageUrl: string; linkUrl: string; sortOrder: number; status: 'active' | 'inactive' }): Promise<{ success: true }> => (await axiosForBackend.put(`/api/admin/banners/${id}`, data)).data;
export const deleteBanner = async (id: string): Promise<{ success: true }> => (await axiosForBackend.delete(`/api/admin/banners/${id}`)).data;
